export default function handler(req, res) {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="pt-BR">',
    '<head>',
    '<meta charset="UTF-8"/>',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0"/>',
    '<title>TrendHunter - Dashboard</title>',
    '<style>',
    'body{font-family:Segoe UI,Tahoma,sans-serif;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);margin:0;color:#333;min-height:100vh}',
    '.container{max-width:1100px;margin:0 auto;padding:20px}',
    '.header{text-align:center;color:#fff;margin:10px 0 30px}',
    '.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px;margin-bottom:28px}',
    '.stat-card{background:#fff;border-radius:14px;padding:22px;box-shadow:0 8px 26px rgba(0,0,0,.08);text-align:center}',
    '.stat-number{font-size:1.7rem;font-weight:700;color:#667eea;margin:6px 0 4px}',
    '.stat-label{font-size:.75rem;letter-spacing:.5px;color:#666;text-transform:uppercase}',
    '.controls{background:#fff;border-radius:14px;padding:24px;margin-bottom:30px;box-shadow:0 8px 26px rgba(0,0,0,.08)}',
    '.control-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid #eee}',
    '.control-row:last-child{margin-bottom:0;border-bottom:none;padding-bottom:0}',
    '.control-title{font-weight:600;margin-bottom:4px}',
    '.control-desc{font-size:.75rem;color:#666;letter-spacing:.3px}',
    '.btn{border:none;border-radius:8px;padding:10px 18px;font-weight:600;cursor:pointer;font-size:.75rem;letter-spacing:.5px;display:inline-flex;align-items:center;gap:6px}',
    '.btn-primary{background:#667eea;color:#fff}',
    '.btn-success{background:#40c057;color:#fff}',
    '.btn-warning{background:#ffd43b;color:#333}',
    '.logs{background:#111;color:#06d706;font-family:Courier New,monospace;padding:18px;border-radius:14px;font-size:.7rem;max-height:340px;overflow-y:auto;margin:30px 0}',
    '.status-indicator{width:10px;height:10px;border-radius:50%;display:inline-block;margin-right:6px}',
    '.status-online{background:#40c057}',
    '.status-offline{background:#fa5252}',
    '.status-warning{background:#ffd43b}',
    '.footer{text-align:center;color:#fff;opacity:.85;margin:35px 0 10px;font-size:.7rem}',
    '#auth-overlay{position:fixed;inset:0;background:linear-gradient(135deg,#1e1e2f,#0d0d17);display:flex;align-items:center;justify-content:center;z-index:9999}',
    '@media (max-width:760px){.control-row{flex-direction:column;align-items:stretch;gap:10px}}',
    '</style>',
    '</head>',
    '<body>',
    '<div id="auth-overlay"><div style="background:#fff;max-width:340px;width:100%;padding:1.8rem 1.9rem;border-radius:16px;box-shadow:0 10px 36px -6px rgba(0,0,0,.4);font-family:system-ui">',
    '<h2 style="margin:0 0 1rem;font-size:1.25rem;color:#222;display:flex;align-items:center;gap:.5rem">🔒 Acesso Restrito</h2>',
    '<p style="margin:.2rem 0 1rem;font-size:.7rem;color:#555;line-height:1.45">Digite a senha para acessar. Sessão expira em 60 minutos.</p>',
    '<form id="auth-form" style="display:flex;flex-direction:column;gap:.7rem">',
    '<input type="password" id="auth-password" placeholder="Senha" style="padding:.75rem .9rem;border:2px solid #e4e6ef;border-radius:9px;font-size:.8rem" />',
    '<button type="submit" style="background:#667eea;color:#fff;border:none;padding:.75rem .9rem;font-weight:600;border-radius:9px;font-size:.8rem;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:.4rem;box-shadow:0 4px 14px -3px rgba(102,126,234,.5)">Entrar</button>',
    '<div id="auth-error" style="min-height:16px;font-size:.6rem;color:#d63939;font-weight:500"></div>',
    '<label style="display:flex;align-items:center;gap:.35rem;font-size:.55rem;color:#666;letter-spacing:.5px;text-transform:uppercase;font-weight:600"><input id="remember-session" type="checkbox" style="accent-color:#667eea"/>Manter logado</label>',
    '<button type="button" id="clear-session" style="background:none;border:none;color:#888;font-size:.55rem;cursor:pointer;text-transform:uppercase;letter-spacing:.5px;padding:0;margin-top:-4px;align-self:flex-end">Limpar</button>',
    '</form>',
    '<div style="margin-top:.9rem;padding:.55rem .65rem;background:#f5f7ff;border:1px solid #e3e9ff;border-radius:8px;font-size:.55rem;line-height:1.25;color:#4a4f63">Configure <code style="background:#eef;border-radius:3px;padding:1px 3px">DASHBOARD_PASSWORD</code><br/>POST <code style="background:#eef;border-radius:3px;padding:1px 3px">/api/dashboard-auth</code></div>',
    '</div></div>',
    '<div class="container">',
    '<div class="header"><h1>💰 TrendHunter Dashboard</h1><p style="margin:.3rem 0 0;font-size:.85rem">Painel Interno</p></div>',
    '<div class="stats-grid">',
    '<div class="stat-card"><div class="stat-number" id="total-trends">-</div><div class="stat-label">TENDÊNCIAS</div></div>',
    '<div class="stat-card"><div class="stat-number" id="newsletter-sent">-</div><div class="stat-label">NEWSLETTERS</div></div>',
    '<div class="stat-card"><div class="stat-number" id="premium-subs">-</div><div class="stat-label">PREMIUM</div></div>',
    '<div class="stat-card"><div class="stat-number" id="revenue-estimate">R$ -</div><div class="stat-label">RECEITA</div></div>',
    '</div>',
    '<div class="controls"><h3 style="margin:0 0 14px">🎮 Controles</h3>',
    '<div class="control-row"><div><div class="control-title"><span class="status-indicator status-online"></span>Tendências</div><div class="control-desc">Atualização Google Trends</div></div><button class="btn btn-primary" onclick="executarTendencias()">Atualizar</button></div>',
    '<div class="control-row"><div><div class="control-title"><span class="status-indicator status-online"></span>Monetização</div><div class="control-desc">Distribuição canais</div></div><button class="btn btn-success" onclick="executarMonetizacao()">Distribuir</button></div>',
    '<div class="control-row"><div><div class="control-title"><span class="status-indicator status-warning"></span>Newsletter</div><div class="control-desc">Mailchimp</div></div><button class="btn btn-warning" onclick="testarNewsletter()">Testar</button></div>',
    '<div class="control-row"><div><div class="control-title"><span class="status-indicator status-warning"></span>Telegram</div><div class="control-desc">Bot público</div></div><button class="btn btn-primary" onclick="testarTelegram()">Testar</button></div>',
    '<div class="control-row"><div><div class="control-title"><span class="status-indicator status-offline"></span>WhatsApp</div><div class="control-desc">Premium</div></div><button class="btn btn-success" onclick="testarWhatsApp()">Configurar</button></div>',
    '</div>',
    '<div class="logs" id="system-logs"><div>🚀 Sistema carregado</div><div>📊 Aguardando ações...</div></div>',
    '<div class="controls"><h3 style="margin:0 0 14px">🔧 Status</h3>',
    '<div class="control-row"><div><div class="control-title">Analytics</div><div class="control-desc">G-49T4JYYWMB</div></div><span class="status-indicator status-online"></span><span style="font-size:.7rem">OK</span></div>',
    '<div class="control-row"><div><div class="control-title">AdSense</div><div class="control-desc">Inativo interno</div></div><span class="status-indicator status-warning"></span><span style="font-size:.7rem">LIMIT</span></div>',
    '</div>',
    '<div class="footer">TrendHunter • <span id="last-update">...</span></div>',
    '</div>',
    '<script>',
  '(function(){const o=document.getElementById("auth-overlay"),f=document.getElementById("auth-form"),p=document.getElementById("auth-password"),e=document.getElementById("auth-error"),r=document.getElementById("remember-session"),c=document.getElementById("clear-session"),K="dashboardAuthToken",KE="dashboardAuthExp";function v(){const t=localStorage.getItem(K)||sessionStorage.getItem(K);if(!t)return!1;const x=parseInt(localStorage.getItem(KE)||sessionStorage.getItem(KE)||"0",10);if(Date.now()>x){[localStorage,sessionStorage].forEach(s=>{s.removeItem(K);s.removeItem(KE)});return!1}return t.split(".").length===2}function u(){o.style.opacity="0";o.style.pointerEvents="none";setTimeout(()=>o.remove(),300)}if(v())u();f.addEventListener("submit",async ev=>{ev.preventDefault();e.textContent="";const pw=p.value.trim();if(!pw){e.textContent="Informe a senha";return}const btn=f.querySelector("button[type=submit]");btn.disabled=!0;btn.style.opacity=".6";try{const resp=await fetch("/api/dashboard-auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})});const data=await resp.json();if(!resp.ok)e.textContent=data.error||"Falha";else{(r.checked?localStorage:sessionStorage).setItem(K,data.token);(r.checked?localStorage:sessionStorage).setItem(KE,Date.now()+data.expiresIn*1000);u()}}catch(_){e.textContent="Erro de rede"}finally{btn.disabled=!1;btn.style.opacity="1"}});c.addEventListener("click",()=>{[localStorage,sessionStorage].forEach(s=>{s.removeItem(K);s.removeItem(KE)});e.style.color="#1f6feb";e.textContent="Sessão limpa";p.focus()})})();',
    'function log(m){const box=document.getElementById("system-logs");const t=new Date().toLocaleTimeString();box.innerHTML+=`<div>[${t}] ${m}</div>`;box.scrollTop=box.scrollHeight;}',
    'function executarTendencias(){log("🔄 Tendências (placeholder)...");}',
    'function executarMonetizacao(){log("💰 Distribuição simulada...");setTimeout(()=>log("✅ Concluído"),1200);}',
    'function testarNewsletter(){log("📧 Teste newsletter...");}',
    'function testarTelegram(){log("📱 Teste telegram...");}',
    'function testarWhatsApp(){log("💎 Teste WhatsApp...");}',
    'function atualizarHorario(){const el=document.getElementById("last-update");if(el)el.textContent=new Date().toLocaleString();}',
    'document.addEventListener("DOMContentLoaded",()=>{atualizarHorario();setInterval(atualizarHorario,60000);});',
    '</script>',
    '</body></html>'
  ].join('');
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  return res.status(200).send(html);
}
